### ISSUE TITLE
Wrong OS version

### ISSUE THREAD

**Issue by BullyWiiPlaza** [wiiudev/pyGecko#17]
Users on firmware 5.5.1 report that the returned firmware version by the server is 550 instead of 551 which is irritating. It is caused by calling the following code snippet of the TCP Gecko server:

```
case 0x9A: { /* cmd_os_version */
    /* Little bit of a hack here, the linker script will define the
     * symbol ver to have address of the version number! */
    extern char ver[];
    ((int *)buffer)[0] = (int)ver;
    ret = sendwait(bss, clientfd, buffer, 4);
    CHECK_ERROR(ret < 0);
    break;
}
```

Is this a bug or supposed to happen? I assume the linker script has to be updated to to be aware of 551.

**Comment by CreeperMario** [comment]
There is no difference between 5.5.0 and 5.5.1, except for the Internet Browser app. The kernel itself did not change between 5.5.0 and 5.5.1, and neither did any memory locations. Why do you need to tell the difference between 5.5.0 and 5.5.1?

**Comment by BullyWiiPlaza** [comment]
Well, I don't but users were confused by the 550 message output even though they were on 551. So effectively, I just change it to 55X for instance and that's it.
