### ISSUE TITLE
Feature Request: Memory Search Function

### ISSUE THREAD

**Issue by BullyWiiPlaza** [wiiudev/pyGecko#5]
To create more reliable RAM hacks, it would be great if there was a function for searching the memory till a certain search template comes up. The function prototype should look similar to this:

`int findFirstMatch(int startingAddress, char searchTemplate[])`

The starting address is useful for reducing the searching overhead and allows for picking "less unique" search templates. The function should return the first address where the given search template is found the first time and for example `-1` if it is not found. Since dumping memory over the local network is slow, this has to be [implemented on the server](https://github.com/wiiudev/pyGecko/blob/master/codehandler/main.c) and not on the client side.

In reference to Wii hacking, this is similar to the [F6 codetype](http://www.geckocodes.org/index.php?arsenal=1#F6). Searching server-sided has proven to be very fast, the process completes in less than 1 second instead of several minutes. This would be incredibly useful to have back.

**Comment by dantarion** [comment]
I already have this in my fork of pyGecko, I just need to port it over. The way mine works is that it has a start, end, alignement, and then the array of bytes. It returns an array of all memory locations where the needle was found.

I need to get this into the public pygecko, but it requires a different codehandler

**Comment by BullyWiiPlaza** [comment]
@dantarion 
I'm already using a modified codehandler by Onion_Knight which allows multiple TCP connections. We really need to merge all the goodies into one codehandler since everyone seems to do improvements on their own...

**Comment by dantarion** [comment]
If you have changes that can be easily merged into this, submit a pull request. The issue with my changes is that I almost completely rewrote a bunch of stuff, so I need to merge all of those changes back in by hand.

**Comment by BullyWiiPlaza** [comment]
I didn't do any changes myself so you can go ahead and merge your's :)
